# -*- coding: utf-8 -*-
"""text_model_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aWxXsT9ihaCjhNgPVw1hMTu2bHED-wzn
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install sentencepiece sacremoses
!pip install translate

# Enhanced Mental Health Assistant - Complete Multilingual System

from transformers import AutoTokenizer, AutoModelForSequenceClassification, pipeline, MarianMTModel, MarianTokenizer
import torch
import json
import random
from typing import Dict, List, Tuple, Optional
from datetime import datetime
import re

#
#  LOAD MODEL

YOUR_MODEL_PATH = "/content/drive/MyDrive/text_model_v1"

print(f" Loading model from: {YOUR_MODEL_PATH}")

try:
    tokenizer = AutoTokenizer.from_pretrained(YOUR_MODEL_PATH, local_files_only=True)
    model = AutoModelForSequenceClassification.from_pretrained(YOUR_MODEL_PATH, local_files_only=True)
    classifier = pipeline("text-classification", model=model, tokenizer=tokenizer, top_k=None)
    print(" Model loaded successfully!")
except Exception as e:
    print(f" Failed to load model: {e}")
    raise e

#  TRANSLATION ENGINE

class EnhancedTranslationEngine:
    def __init__(self):
        self.translators = {}
        self.device = "cuda" if torch.cuda.is_available() else "cpu"

        self.translation_models = {
            'ar_to_en': 'Helsinki-NLP/opus-mt-ar-en',
            'tr_to_en': 'Helsinki-NLP/opus-mt-tr-en',
        }

        print(" Loading translation models...")
        try:
            for direction, model_name in self.translation_models.items():
                print(f"  Loading {direction}...")
                tok = MarianTokenizer.from_pretrained(model_name)
                mod = MarianMTModel.from_pretrained(model_name).to(self.device)
                self.translators[direction] = {'tokenizer': tok, 'model': mod}
            print(" Translation models loaded!")
        except Exception as e:
            print(f" Translation models error: {e}")

    def translate(self, text: str, source_lang: str, target_lang: str = 'en') -> str:
        if source_lang == target_lang:
            return text

        direction = f"{source_lang}_to_{target_lang}"

        if direction not in self.translators:
            return self._keyword_translate(text, source_lang)

        try:
            translator = self.translators[direction]
            sentences = re.split(r'[.!?؟]+', text)
            translated = []

            for sent in sentences:
                if sent.strip():
                    inputs = translator['tokenizer'](sent, return_tensors="pt", padding=True).to(self.device)
                    output = translator['model'].generate(**inputs, max_length=512)
                    translated.append(translator['tokenizer'].decode(output[0], skip_special_tokens=True))

            return " ".join(translated)
        except:
            return self._keyword_translate(text, source_lang)

    def _keyword_translate(self, text: str, source_lang: str) -> str:
        maps = {
            'ar': {'حزين': 'sad', 'قلق': 'anxious', 'تعب': 'tired', 'نوم': 'sleep'},
            'tr': {'üzgün': 'sad', 'kaygılı': 'anxious', 'yorgun': 'tired', 'uyku': 'sleep'}
        }

        if source_lang not in maps:
            return text.lower()

        words = text.lower().split()
        return ' '.join([maps[source_lang].get(w, w) for w in words])

translation_engine = EnhancedTranslationEngine()


#  MULTILINGUAL INTERFACE


MULTILINGUAL_SYSTEM = {
    'ar':
        'welcome': "مرحباً بك! \nأنا هنا لأسمعك وأفهم ما تمر به.",
        'share_feelings': " أخبرني بما تشعر:",
        'exploratory_title': " أسئلة لفهم أفضل لحالتك:",
        'analyzing': "جاري التحليل...",
        'results_title': " نتائج التحليل:",
        'category': " الفئة:",
        'confidence': " الثقة:",
        'severity': " الشدة:",
        'immediate_support': " دعم فوري:",
        'self_care': " رعاية ذاتية:",
        'professional_guidance': " توجيه مهني:",
        'next_steps': " خطوات تالية:",
        'remember': " مشاركتك خطوة شجاعة نحو الشفاء",
        'continue_chat': " متابعة؟ (نعم/لا)",
        'save_prompt': " حفظ؟ (نعم/لا):",
        'language_detected': "اللغة:"
    },
    'en': {
        'welcome': "Welcome! \nI'm here to listen and understand.",
        'share_feelings': " Tell me how you feel:",
        'exploratory_title': " Questions to better understand:",
        'analyzing': " Analyzing...",
        'results_title': " Analysis Results:",
        'category': " Category:",
        'confidence': "Confidence:",
        'severity': "Severity:",
        'immediate_support': " Immediate Support:",
        'self_care': "Self-Care:",
        'professional_guidance': "Professional Guidance:",
        'next_steps': "Next Steps:",
        'remember': " Sharing is a brave step toward healing",
        'continue_chat': " Continue? (yes/no)",
        'save_prompt': " Save? (yes/no):",
        'language_detected': "Language:"
    },
    'tr': {
        'welcome': "Hoş geldiniz! \nSizi dinlemek için buradayım.",
        'share_feelings': " Nasıl hissettiğinizi anlatın:",
        'exploratory_title': " Daha iyi anlamak için sorular:",
        'analyzing': "Analiz ediliyor...",
        'results_title': "Analiz Sonuçları:",
        'category': " Kategori:",
        'confidence': "Güven:",
        'severity': "Şiddet:",
        'immediate_support': " Acil Destek:",
        'self_care': "Öz Bakım:",
        'professional_guidance': " Profesyonel Rehberlik:",
        'next_steps': " Sonraki Adımlar:",
        'remember': " Paylaşmak iyileşmeye doğru cesur bir adımdır",
        'continue_chat': " Devam? (evet/hayır)",
        'save_prompt': " Kaydet? (evet/hayır):",
        'language_detected': " Dil:"
    }
}

# =============================================================================
# 📚 ENHANCED QUESTIONS -
# =============================================================================

ENHANCED_QUESTIONS = {
    'ar': [
        "منذ متى تشعر بهذه الطريقة؟ (أيام/أسابيع/شهور)",
        "على مقياس 1-10، كم شدة هذه المشاعر؟",
        "كيف تؤثر على عملك/دراستك؟",
        "كيف تأثر نومك وشهيتك؟",
        "هل تجد صعوبة في التركيز؟",
        "هل لديك دعم اجتماعي (عائلة/أصدقاء)؟",
        "ما الذي يحسّن حالتك؟",
        "هل راودتك أفكار سلبية عن نفسك؟"
    ],
    'en': [
        "How long have you felt this way? (days/weeks/months)",
        "On a scale 1-10, how intense are these feelings?",
        "How does it affect your work/studies?",
        "How has your sleep and appetite been?",
        "Do you have difficulty concentrating?",
        "Do you have social support (family/friends)?",
        "What usually improves your condition?",
        "Have you had negative thoughts about yourself?"
    ],
    'tr': [
        "Ne zamandır böyle hissediyorsunuz? (gün/hafta/ay)",
        "1-10 arası, bu duygular ne kadar yoğun?",
        "İşinizi/eğitiminizi nasıl etkiliyor?",
        "Uykunuz ve iştahınız nasıl?",
        "Konsantre olmakta zorluk çekiyor musunuz?",
        "Sosyal desteğiniz var mı (aile/arkadaşlar)?",
        "Durumunuzu genellikle ne iyileştirir?",
        "Kendiniz hakkında olumsuz düşünceleriniz oldu mu?"
    ]
}

# =============================================================================
# 💎 COMPREHENSIVE RECOMMENDATIONS -
# =============================================================================

COMPREHENSIVE_RECOMMENDATIONS = {
    'ADHD': {
        'ar': {
            'mild': {
                'immediate': [
                    "استخدم تقنية البومودورو (25 دقيقة عمل، 5 دقائق راحة)",
                    "اكتب 3 مهام رئيسية يومياً",
                    "قلل المشتتات: أغلق إشعارات الهاتف"
                ],
                'self_care': [
                    "مارس الرياضة 30 دقيقة يومياً",
                    "نم بانتظام 7-8 ساعات",
                    "تناول أطعمة غنية بالأوميغا 3"
                ],
                'professional': "استشر أخصائياً نفسياً لتقييم ADHD. العلاج السلوكي فعّال جداً.",
                'next_steps': [
                    "احجز تقييم ADHD شامل",
                    "تعلم تقنيات إدارة الوقت",
                    "انضم لمجموعات دعم ADHD"
                ]
            },
            'moderate': {
                'immediate': [
                    "قسّم المهام لخطوات صغيرة قابلة للتنفيذ",
                    "استخدم مؤقتات وتنبيهات للمهام",
                    "خصص مكان عمل منظم تماماً"
                ],
                'self_care': [
                    "مارس التأمل واليقظة الذهنية 15 دقيقة يومياً",
                    "احتفظ بدفتر لتنظيم أفكارك",
                    "خصص وقتاً للهوايات المحببة"
                ],
                'professional': "استشر طبيباً نفسياً متخصصاً. قد تحتاج علاجاً دوائياً مع العلاج السلوكي.",
                'next_steps': [
                    "ابدأ علاجاً سلوكياً معرفياً",
                    "ناقش الخيارات الدوائية مع الطبيب",
                    "تدرب على تقنيات التركيز"
                ]
            },
            'severe': {
                'immediate': [
                    "احصل على تقييم طبي فوري",
                    "أخبر عائلتك/مديرك بحالتك",
                    "خذ إجازة إذا لزم الأمر"
                ],
                'self_care': [
                    "التزم بروتين صارم ومنظم",
                    "استخدم تطبيقات متخصصة لـ ADHD",
                    "اطلب دعم الأسرة المباشر"
                ],
                'professional': " ضروري: استشارة طبيب نفسي فوراً. العلاج المكثف ضروري.",
                'next_steps': [
                    "ابدأ علاجاً دوائياً تحت إشراف طبي",
                    "جلسات علاجية أسبوعية",
                    "تطوير خطة تعليمية/عملية مخصصة"
                ]
            }
        },
        'en': {
            'mild': {
                'immediate': [
                    "Use Pomodoro technique (25min work, 5min break)",
                    "Write 3 main daily tasks",
                    "Reduce distractions: turn off phone notifications"
                ],
                'self_care': [
                    "Exercise 30 minutes daily",
                    "Sleep regularly 7-8 hours",
                    "Eat omega-3 rich foods"
                ],
                'professional': "Consult a psychologist for ADHD assessment. Behavioral therapy is very effective.",
                'next_steps': [
                    "Book comprehensive ADHD evaluation",
                    "Learn time management techniques",
                    "Join ADHD support groups"
                ]
            },
            'moderate': {
                'immediate': [
                    "Break tasks into small actionable steps",
                    "Use timers and reminders for tasks",
                    "Designate a fully organized workspace"
                ],
                'self_care': [
                    "Practice meditation and mindfulness 15 min daily",
                    "Keep a journal to organize thoughts",
                    "Allocate time for enjoyable hobbies"
                ],
                'professional': "Consult a specialized psychiatrist. You may need medication with behavioral therapy.",
                'next_steps': [
                    "Start cognitive behavioral therapy",
                    "Discuss medication options with doctor",
                    "Train in focus techniques"
                ]
            },
            'severe': {
                'immediate': [
                    "Get immediate medical assessment",
                    "Inform family/manager of your condition",
                    "Take leave if necessary"
                ],
                'self_care': [
                    "Stick to strict organized routine",
                    "Use specialized ADHD apps",
                    "Request direct family support"
                ],
                'professional': " URGENT: Consult psychiatrist immediately. Intensive treatment necessary.",
                'next_steps': [
                    "Start medication under medical supervision",
                    "Weekly therapy sessions",
                    "Develop customized educational/work plan"
                ]
            }
        },
        'tr': {
            'mild': {
                'immediate': [
                    "Pomodoro tekniği kullanın (25dk çalışma, 5dk mola)",
                    "Günlük 3 ana görev yazın",
                    "Dikkat dağıtıcıları azaltın: telefon bildirimlerini kapatın"
                ],
                'self_care': [
                    "Günde 30 dakika egzersiz yapın",
                    "Düzenli 7-8 saat uyuyun",
                    "Omega-3 açısından zengin yiyecekler tüketin"
                ],
                'professional': "DEHB değerlendirmesi için bir psikolog danışın. Davranışçı terapi çok etkilidir.",
                'next_steps': [
                    "Kapsamlı DEHB değerlendirmesi rezervasyonu yapın",
                    "Zaman yönetimi tekniklerini öğrenin",
                    "DEHB destek gruplarına katılın"
                ]
            },
            'moderate': {
                'immediate': [
                    "Görevleri küçük uygulanabilir adımlara bölün",
                    "Görevler için zamanlayıcılar ve hatırlatıcılar kullanın",
                    "Tamamen organize bir çalışma alanı belirleyin"
                ],
                'self_care': [
                    "Günde 15 dakika meditasyon ve farkındalık yapın",
                    "Düşüncelerinizi düzenlemek için günlük tutun",
                    "Keyifli hobilere zaman ayırın"
                ],
                'professional': "Uzman bir psikiyatriste danışın. Davranışçı terapiyle birlikte ilaca ihtiyacınız olabilir.",
                'next_steps': [
                    "Bilişsel davranışçı terapiye başlayın",
                    "Doktorla ilaç seçeneklerini tartışın",
                    "Odaklanma tekniklerinde antrenman yapın"
                ]
            },
            'severe': {
                'immediate': [
                    "Hemen tıbbi değerlendirme alın",
                    "Durumunuzu aile/yöneticinize bildirin",
                    "Gerekirse izin alın"
                ],
                'self_care': [
                    "Sıkı organize rutine bağlı kalın",
                    "Özel DEHB uygulamaları kullanın",
                    "Doğrudan aile desteği isteyin"
                ],
                'professional': " ACİL: Hemen psikiyatriste başvurun. Yoğun tedavi gerekli.",
                'next_steps': [
                    "Tıbbi gözetim altında ilaç tedavisine başlayın",
                    "Haftalık terapi seansları",
                    "Özelleştirilmiş eğitim/iş planı geliştirin"
                ]
            }
        }
    },

    'Anxiety': {
        'ar': {
            'mild': {
                'immediate': [
                    "تقنية 5-4-3-2-1: 5 أشياء تراها، 4 تلمسها، 3 تسمعها، 2 تشمها، 1 تتذوقه",
                    "تنفس عميق: 4 ثوان شهيق، 4 حبس، 4 زفير",
                    "اكتب مخاوفك وقيّم احتماليتها"
                ],
                'self_care': [
                    "تأمل 10 دقائق يومياً",
                    "قلل الكافيين والسكر",
                    "مارس اليوغا أو الرياضة الخفيفة"
                ],
                'professional': "العلاج السلوكي المعرفي فعّال جداً للقلق. استشر معالجاً نفسياً.",
                'next_steps': [
                    "تعلم تقنيات التنفس والاسترخاء",
                    "انضم لورشة إدارة القلق",
                    "احتفظ بمذكرة للقلق"
                ]
            },
            'moderate': {
                'immediate': [
                    "مارس استرخاء العضلات التدريجي",
                    "استمع لموسيقى هادئة",
                    "تجنب المحفزات المعروفة"
                ],
                'self_care': [
                    "تأمل 15-20 دقيقة يومياً",
                    "احتفظ بروتين نوم صارم",
                    "تجنب الأخبار المقلقة قبل النوم"
                ],
                'professional': "استشر طبيباً نفسياً. قد تحتاج علاجاً دوائياً قصير المدى مع العلاج النفسي.",
                'next_steps': [
                    "ابدأ جلسات علاج معرفي سلوكي أسبوعية",
                    "ناقش الأدوية المضادة للقلق",
                    "تدرب على مواجهة المخاوف تدريجياً"
                ]
            },
            'severe': {
                'immediate': [
                    " تواصل مع أحد الأحباء فوراً",
                    "إذا شعرت بنوبة هلع، اجلس وركز على التنفس",
                    "اذهب لمكان آمن وهادئ"
                ],
                'self_care': [
                    "لا تبقَ وحيداً",
                    "تجنب الكحول والمنشطات تماماً",
                    "التزم بروتين يومي بسيط"
                ],
                'professional': " ضروري: استشارة طبيب نفسي فوراً. القلق الشديد يحتاج علاجاً مكثفاً. خط الطوارئ متاح.",
                'next_steps': [
                    "علاج دوائي فوري تحت إشراف طبي",
                    "جلسات علاجية مكثفة (2-3 أسبوعياً)",
                    "تطوير خطة طوارئ للقلق"
                ]
            }
        },
        'en': {
            'mild': {
                'immediate': [
                    "5-4-3-2-1 technique: 5 see, 4 touch, 3 hear, 2 smell, 1 taste",
                    "Deep breathing: 4sec inhale, 4 hold, 4 exhale",
                    "Write worries and assess their probability"
                ],
                'self_care': [
                    "Meditate 10 minutes daily",
                    "Reduce caffeine and sugar",
                    "Practice yoga or light exercise"
                ],
                'professional': "Cognitive Behavioral Therapy very effective for anxiety. Consult therapist.",
                'next_steps': [
                    "Learn breathing and relaxation techniques",
                    "Join anxiety management workshop",
                    "Keep an anxiety journal"
                ]
            },
            'moderate': {
                'immediate': [
                    "Practice progressive muscle relaxation",
                    "Listen to calming music",
                    "Avoid known triggers"
                ],
                'self_care': [
                    "Meditate 15-20 minutes daily",
                    "Maintain strict sleep routine",
                    "Avoid anxiety-inducing news before bed"
                ],
                'professional': "Consult psychiatrist. May need short-term medication with psychotherapy.",
                'next_steps': [
                    "Start weekly cognitive behavioral therapy",
                    "Discuss anti-anxiety medications",
                    "Gradually train in facing fears"
                ]
            },
            'severe': {
                'immediate': [
                    "🚨 Contact loved one immediately",
                    "If panic attack, sit and focus on breathing",
                    "Go to safe, quiet place"
                ],
                'self_care': [
                    "Don't stay alone",
                    "Avoid alcohol and stimulants completely",
                    "Stick to simple daily routine"
                ],
                'professional': "URGENT: Consult psychiatrist immediately. Severe anxiety needs intensive treatment. Emergency line available.",
                'next_steps': [
                    "Immediate medication under medical supervision",
                    "Intensive therapy sessions (2-3 weekly)",
                    "Develop anxiety emergency plan"
                ]
            }
        },
        'tr': {
            'mild': {
                'immediate': [
                    "5-4-3-2-1 tekniği: 5 gör, 4 dokun, 3 duy, 2 kokla, 1 tat",
                    "Derin nefes: 4sn içe al, 4 tut, 4 ver",
                    "Endişeleri yazın ve olasılıklarını değerlendirin"
                ],
                'self_care': [
                    "Günde 10 dakika meditasyon",
                    "Kafein ve şekeri azaltın",
                    "Yoga veya hafif egzersiz yapın"
                ],
                'professional': "Bilişsel Davranışçı Terapi kaygı için çok etkili. Terapiste danışın.",
                'next_steps': [
                    "Nefes alma ve gevşeme tekniklerini öğrenin",
                    "Kaygı yönetimi atölyesine katılın",
                    "Kaygı günlüğü tutun"
                ]
            },
            'moderate': {
                'immediate': [
                    "Aşamalı kas gevşetme yapın",
                    "Sakinleştirici müzik dinleyin",
                    "Bilinen tetikleyicilerden kaçının"
                ],
                'self_care': [
                    "Günde 15-20 dakika meditasyon",
                    "Sıkı uyku rutini sürdürün",
                    "Yatmadan önce kaygı verici haberlerden kaçının"
                ],
                'professional': "Psikiyatriste danışın. Psikoterapiyle kısa süreli ilaca ihtiyacınız olabilir.",
                'next_steps': [
                    "Haftalık bilişsel davranışçı terapiye başlayın",
                    "Anti-anksiyete ilaçlarını tartışın",
                    "Korkularla yüzleşmede kademeli antrenman"
                ]
            },
            'severe': {
                'immediate': [
                    "Hemen sevdiklerinizle iletişime geçin",
                    "Panik atakta oturun ve nefese odaklanın",
                    "Güvenli, sessiz yere gidin"
                ],
                'self_care': [
                    "Yalnız kalmayın",
                    "Alkol ve uyarıcılardan tamamen kaçının",
                    "Basit günlük rutine bağlı kalın"
                ],
                'professional': " ACİL: Hemen psikiyatriste başvurun. Şiddetli kaygı yoğun tedavi gerektirir. Acil hat: 182",
                'next_steps': [
                    "Tıbbi gözetim altında hemen ilaç tedavisi",
                    "Yoğun terapi seansları (haftada 2-3)",
                    "Kaygı acil durum planı geliştirin"
                ]
            }
        }
    },

    'Depression': {
        'ar': {
            'mild': {
                'immediate': [
                    "اتصل بصديق اليوم",
                    "اخرج للشمس 15 دقيقة",
                    "ضع هدفاً صغيراً (الاستحمام مثلاً)"
                ],
                'self_care': [
                    "روتين نوم منتظم",
                    "مشي 10-15 دقيقة يومياً",
                    "تناول وجبات منتظمة"
                ],
                'professional': "الاكتئاب قابل للعلاج. استشر معالجاً نفسياً.",
                'next_steps': [
                    "احجز موعد علاج نفسي",
                    "انضم لمجموعة دعم",
                    "مارس نشاطاً كنت تحبه"
                ]
            },
            'moderate': {
                'immediate': [
                    "لا تعزل نفسك",
                    "اكتب 3 أمور إيجابية يومياً",
                    "تواصل مع الداعمين"
                ],
                'self_care': [
                    "روتين يومي ثابت",
                    "رياضة منتظمة",
                    "قلل وسائل التواصل"
                ],
                'professional': "استشر طبيباً نفسياً. قد تحتاج علاجاً دوائياً مع العلاج النفسي.",
                'next_steps': [
                    "علاج نفسي أسبوعي",
                    "ناقش الأدوية المضادة للاكتئاب",
                    "تابع مع الطبيب منتظماً"
                ]
            },
            'severe': {
                'immediate': [
                    "لا تبقَ وحيداً",
                    "أخبر شخصاً تثق به فوراً",
                    "إذا راودتك أفكار انتحارية: اتصل بخط الطوارئ"
                ],
                'self_care': [
                    "ابقَ مع شخص داعم",
                    "أبعد أدوات الضرر",
                    "التزم بالعلاج"
                ],
                'professional': " طوارئ! اذهب لطبيب نفسي أو طوارئ المستشفى فوراً. الاكتئاب الحاد خطير. خط الدعم متاح 24/7",
                'next_steps': [
                    "دخول المستشفى إذا لزم",
                    "علاج دوائي مكثف فوري",
                    "متابعة يومية مع فريق طبي"
                ]
            }
        },
        'en': {
            'mild': {
                'immediate': [
                    "Call a friend today",
                    "Go out in sun 15 minutes",
                    "Set small goal (like shower)"
                ],
                'self_care': [
                    "Regular sleep routine",
                    "Walk 10-15 minutes daily",
                    "Eat regular meals"
                ],
                'professional': "Depression is treatable. Consult therapist.",
                'next_steps': [
                    "Book therapy appointment",
                    "Join support group",
                    "Do activity you used to love"
                ]
            },
            'moderate': {
                'immediate': [
                    "Don't isolate yourself",
                    "Write 3 positive things daily",
                    "Contact supporters"
                ],
                'self_care': [
                    "Fixed daily routine",
                    "Regular exercise",
                    "Reduce social media"
                ],
                'professional': "Consult psychiatrist. May need medication with therapy.",
                'next_steps': [
                    "Weekly psychotherapy",
                    "Discuss antidepressants",
                    "Regular doctor follow-up"
                ]
            },
            'severe': {
                'immediate': [
                    " Don't stay alone",
                    "Tell trusted person immediately",
                    "If suicidal thoughts: call emergency"
                ],
                'self_care': [
                    "Stay with supportive person",
                    "Remove harm tools",
                    "Stick to treatment"
                ],
                'professional': " EMERGENCY! Go to psychiatrist or hospital ER immediately. Severe depression is dangerous. Support line 24/7",
                'next_steps': [
                    "Hospital admission if needed",
                    "Immediate intensive medication",
                    "Daily medical team follow-up"
                ]
            }
        },
        'tr': {
            'mild': {
                'immediate': [
                    "Bugün bir arkadaşı arayın",
                    "15 dakika güneşe çıkın",
                    "Küçük hedef koyun (duş gibi)"
                ],
                'self_care': [
                    "Düzenli uyku rutini",
                    "Günde 10-15 dakika yürüyüş",
                    "Düzenli öğün yiyin"
                ],
                'professional': "Depresyon tedavi edilebilir. Terapiste danışın.",
                'next_steps': [
                    "Terapi randevusu alın",
                    "Destek grubuna katılın",
                    "Sevdiğiniz aktivite yapın"
                ]
            },
            'moderate': {
                'immediate': [
                    "Kendinizi izole etmeyin",
                    "Günde 3 olumlu şey yazın",
                    "Destekleyicilerle iletişim kurun"
                ],
                'self_care': [
                    "Sabit günlük rutin",
                    "Düzenli egzersiz",
                    "Sosyal medyayı azaltın"
                ],
                'professional': "Psikiyatriste danışın. Terapiyle birlikte ilaca ihtiyacınız olabilir.",
                'next_steps': [
                    "Haftalık psikoterapi",
                    "Antidepresanları tartışın",
                    "Düzenli doktor takibi"
                ]
            },
            'severe': {
                'immediate': [
                    " Yalnız kalmayın",
                    "Güvendiğiniz birine hemen söyleyin",
                    "İntihar düşünceleri varsa: acil hattı arayın"
                ],
                'self_care': [
                    "Destekleyici biriyle kalın",
                    "Zarar araçlarını kaldırın",
                    "Tedaviye bağlı kalın"
                ],
                'professional': "🚨 ACİL! Hemen psikiyatriste veya hastane acil servisine gidin. Şiddetli depresyon tehlikelidir. Destek hattı 24/7: 182",
                'next_steps': [
                    "Gerekirse hastaneye yatış",
                    "Hemen yoğun ilaç tedavisi",
                    "Günlük tıbbi ekip takibi"
                ]
            }
        }
    },

    'Stress': {
        'ar': {
            'mild': {
                'immediate': ["تنفس عميق 5 دقائق", "خذ استراحة 10 دقائق", "اكتب قائمة أولويات"],
                'self_care': ["رياضة منتظمة", "نوم كافٍ", "هوايات مريحة"],
                'professional': "تقنيات إدارة التوتر مع مختص مفيدة جداً.",
                'next_steps': ["تعلم تقنيات الاسترخاء", "ورشة إدارة التوتر", "تنظيم الوقت"]
            },
            'moderate': {
                'immediate': ["حدد مصادر التوتر", "فوّض بعض المهام", "قل 'لا' للزائد"],
                'self_care': ["تأمل يومي", "تقليل الكافيين", "دعم اجتماعي"],
                'professional': "استشر معالجاً لتطوير استراتيجيات التكيف.",
                'next_steps': ["علاج نفسي", "تحسين إدارة الوقت", "تحديد الحدود"]
            },
            'severe': {
                'immediate': [" خذ إجازة", "اطلب دعماً فورياً", "قلل الالتزامات"],
                'self_care': ["راحة تامة", "بيئة هادئة", "دعم مكثف"],
                'professional': " استشارة عاجلة. التوتر المزمن الشديد يؤثر على الصحة.",
                'next_steps': ["علاج مكثف", "تغيير نمط الحياة", "إعادة التقييم"]
            }
        },
        'en': {
            'mild': {
                'immediate': ["Deep breathing 5 min", "Take 10 min break", "Write priority list"],
                'self_care': ["Regular exercise", "Adequate sleep", "Relaxing hobbies"],
                'professional': "Stress management techniques with specialist very helpful.",
                'next_steps': ["Learn relaxation techniques", "Stress management workshop", "Time organization"]
            },
            'moderate': {
                'immediate': ["Identify stress sources", "Delegate some tasks", "Say 'no' to excess"],
                'self_care': ["Daily meditation", "Reduce caffeine", "Social support"],
                'professional': "Consult therapist to develop coping strategies.",
                'next_steps': ["Psychotherapy", "Improve time management", "Set boundaries"]
            },
            'severe': {
                'immediate': [" Take leave", "Request immediate support", "Reduce commitments"],
                'self_care': ["Complete rest", "Quiet environment", "Intensive support"],
                'professional': " Urgent consultation. Severe chronic stress affects health.",
                'next_steps': ["Intensive treatment", "Lifestyle change", "Reassessment"]
            }
        },
        'tr': {
            'mild': {
                'immediate': ["5 dk derin nefes", "10 dk mola", "Öncelik listesi yazın"],
                'self_care': ["Düzenli egzersiz", "Yeterli uyku", "Rahatlatıcı hobiler"],
                'professional': "Uzmanla stres yönetimi teknikleri çok yardımcı.",
                'next_steps': ["Gevşeme tekniklerini öğrenin", "Stres yönetimi atölyesi", "Zaman organizasyonu"]
            },
            'moderate': {
                'immediate': ["Stres kaynaklarını belirleyin", "Bazı görevleri devredin", "Fazlaya 'hayır' deyin"],
                'self_care': ["Günlük meditasyon", "Kafeini azaltın", "Sosyal destek"],
                'professional': "Başa çıkma stratejileri geliştirmek için terapiste danışın.",
                'next_steps': ["Psikoterapi", "Zaman yönetimini iyileştirin", "Sınırlar belirleyin"]
            },
            'severe': {
                'immediate': [" İzin alın", "Hemen destek isteyin", "Taahhütleri azaltın"],
                'self_care': ["Tam dinlenme", "Sessiz ortam", "Yoğun destek"],
                'professional': "Acil danışma. Şiddetli kronik stres sağlığı etkiler. 182",
                'next_steps': ["Yoğun tedavi", "Yaşam tarzı değişikliği", "Yeniden değerlendirme"]
            }
        }
    },

    'Suicidal': {
        'ar': {
            'mild': {
                'immediate': [" اتصل بخط الطوارئ فوراً", "لا تبقَ وحيداً", "أبعد أدوات الضرر"],
                'self_care': ["ابقَ مع أحبائك", "تجنب الكحول", "اكتب أسباب البقاء"],
                'professional': " طوارئ! اذهب لطوارئ المستشفى. حياتك ثمينة!",
                'next_steps': ["تقييم نفسي فوري", "خطة أمان", "متابعة مكثفة"]
            },
            'moderate': {
                'immediate': [" اتصل بالطوارئ الآن", "أخبر عائلتك فوراً", "اذهب لمكان آمن"],
                'self_care': ["لا تبقَ وحيداً أبداً", "أزل كل وسائل الضرر", "التزم بالعلاج"],
                'professional': " حالة طوارئ! دخول المستشفى ضروري. اتصل بخط الحياة.",
                'next_steps': ["دخول فوري للمستشفى", "علاج مكثف", "مراقبة 24/7"]
            },
            'severe': {
                'immediate': [" اتصل بـ 911 أو الطوارئ الآن", "اذهب للمستشفى فوراً", "لا تترك الشخص وحيداً"],
                'self_care': ["مراقبة مستمرة", "بيئة آمنة تماماً", "دعم فوري"],
                'professional': " حالة طوارئ قصوى! دخول فوري للمستشفى. حياتك مهمة!",
                'next_steps': ["دخول المستشفى فوراً", "رعاية نفسية مكثفة", "خطة سلامة شاملة"]
            }
        },
        'en': {
            'mild': {
                'immediate': [" Call emergency hotline now", "Don't stay alone", "Remove harm tools"],
                'self_care': ["Stay with loved ones", "Avoid alcohol", "Write reasons to stay"],
                'professional': "EMERGENCY! Go to hospital ER. Your life is precious!",
                'next_steps': ["Immediate psych evaluation", "Safety plan", "Intensive follow-up"]
            },
            'moderate': {
                'immediate': [" Call emergency NOW", "Tell family immediately", "Go to safe place"],
                'self_care': ["Never stay alone", "Remove all harm means", "Stick to treatment"],
                'professional': "EMERGENCY! Hospital admission necessary. Call lifeline.",
                'next_steps': ["Immediate hospital admission", "Intensive treatment", "24/7 monitoring"]
            },
            'severe': {
                'immediate': ["Call 911 or emergency NOW", "Go to hospital immediately", "Don't leave person alone"],
                'self_care': ["Continuous monitoring", "Completely safe environment", "Immediate support"],
                'professional': " CRITICAL EMERGENCY! Immediate hospital admission. Your life matters!",
                'next_steps': ["Hospital admission immediately", "Intensive psychiatric care", "Comprehensive safety plan"]
            }
        },
        'tr': {
            'mild': {
                'immediate': [" Acil hattı şimdi arayın: 182", "Yalnız kalmayın", "Zarar araçlarını kaldırın"],
                'self_care': ["Sevdiklerinizle kalın", "Alkolden kaçının", "Kalma nedenlerini yazın"],
                'professional': "ACİL! Hastane acil servisine gidin. Hayatınız değerli!",
                'next_steps': ["Hemen psikiyatrik değerlendirme", "Güvenlik planı", "Yoğun takip"]
            },
            'moderate': {
                'immediate': [" ŞİMDİ acil arayın: 182", "Aileye hemen söyleyin", "Güvenli yere gidin"],
                'self_care': ["Asla yalnız kalmayın", "Tüm zarar araçlarını kaldırın", "Tedaviye bağlı kalın"],
                'professional': "ACİL DURUM! Hastaneye yatış gerekli. Yaşam hattını arayın: 182",
                'next_steps': ["Hemen hastaneye yatış", "Yoğun tedavi", "24/7 izleme"]
            },
            'severe': {
                'immediate': [" 112'yi ŞİMDİ arayın", "Hemen hastaneye gidin", "Kişiyi yalnız bırakmayın"],
                'self_care': ["Sürekli gözetim", "Tamamen güvenli ortam", "Anında destek"],
                'professional': " KRİTİK ACİL! Hemen hastaneye yatış. Hayatınız önemli! 182/112",
                'next_steps': ["Hemen hastaneye yatış", "Yoğun psikiyatrik bakım", "Kapsamlı güvenlik planı"]
            }
        }
    },

    'Normal': {
        'ar': {
            'mild': {
                'immediate': ["حافظ على عاداتك الصحية", "احتفل بإنجازاتك", "شارك الإيجابية"],
                'self_care': ["رياضة منتظمة", "علاقات اجتماعية", "هوايات وتطوير"],
                'professional': "أنت بحالة جيدة! الفحوصات الدورية مفيدة.",
                'next_steps': ["استمر بالعادات الصحية", "طوّر مهارات التكيف", "اقرأ عن الصحة النفسية"]
            }
        },
        'en': {
            'mild': {
                'immediate': ["Maintain healthy habits", "Celebrate achievements", "Share positivity"],
                'self_care': ["Regular exercise", "Social relationships", "Hobbies and development"],
                'professional': "You're in good shape! Periodic check-ups helpful.",
                'next_steps': ["Continue healthy habits", "Develop coping skills", "Read about mental health"]
            }
        },
        'tr': {
            'mild': {
                'immediate': ["Sağlıklı alışkanlıklarınızı sürdürün", "Başarılarınızı kutlayın", "Pozitiflik paylaşın"],
                'self_care': ["Düzenli egzersiz", "Sosyal ilişkiler", "Hobiler ve gelişim"],
                'professional': "İyi durumdasınız! Periyodik kontroller faydalı.",
                'next_steps': ["Sağlıklı alışkanlıklara devam", "Başa çıkma becerileri geliştirin", "Ruh sağlığı hakkında okuyun"]
            }
        }
    },

    'Bipolar': {
        'ar': {
            'mild': {
                'immediate': ["راقب المزاج يومياً", "نوم منتظم 7-8 ساعات", "تجنب الكحول"],
                'self_care': ["روتين يومي ثابت", "مذكرة مزاجية", "غذاء متوازن"],
                'professional': "الاضطراب ثنائي القطب يحتاج متابعة منتظمة مع طبيب.",
                'next_steps': ["مواعيد منتظمة", "التزام بالدواء", "دعم العائلة"]
            },
            'moderate': {
                'immediate': ["التزم بالدواء", "تابع الطبيب أسبوعياً", "تجنب المحفزات"],
                'self_care': ["نمط حياة منتظم", "دعم اجتماعي", "تعلم العلامات المبكرة"],
                'professional': "متابعة طبية دقيقة ضرورية. لا توقف الدواء.",
                'next_steps': ["علاج دوائي منتظم", "علاج نفسي", "خطة طوارئ"]
            },
            'severe': {
                'immediate': ["🚨 اتصل بالطبيب فوراً", "لا توقف الدواء", "اطلب دعم العائلة"],
                'self_care': ["مراقبة مكثفة", "بيئة مستقرة", "التزام صارم"],
                'professional': "🚨 حالة حرجة! قد تحتاج دخول المستشفى. اتصل بالطبيب.",
                'next_steps': ["تقييم فوري", "تعديل الدواء", "مراقبة يومية"]
            }
        },
        'en': {
            'mild': {
                'immediate': ["Monitor mood daily", "Regular sleep 7-8 hours", "Avoid alcohol"],
                'self_care': ["Fixed daily routine", "Mood diary", "Balanced diet"],
                'professional': "Bipolar disorder needs regular medical follow-up.",
                'next_steps': ["Regular appointments", "Medication adherence", "Family support"]
            },
            'moderate': {
                'immediate': ["Stick to medication", "See doctor weekly", "Avoid triggers"],
                'self_care': ["Regular lifestyle", "Social support", "Learn early signs"],
                'professional': "Careful medical follow-up necessary. Don't stop medication.",
                'next_steps': ["Regular medication", "Psychotherapy", "Emergency plan"]
            },
            'severe': {
                'immediate': [" Call doctor immediately", "Don't stop medication", "Request family support"],
                'self_care': ["Intensive monitoring", "Stable environment", "Strict adherence"],
                'professional': " CRITICAL! May need hospitalization. Call doctor.",
                'next_steps': ["Immediate evaluation", "Medication adjustment", "Daily monitoring"]
            }
        },
        'tr': {
            'mild': {
                'immediate': ["Ruh halini günlük izle", "Düzenli 7-8 saat uyku", "Alkolden kaçın"],
                'self_care': ["Sabit günlük rutin", "Ruh hali günlüğü", "Dengeli diyet"],
                'professional': "Bipolar bozukluk düzenli tıbbi takip gerektirir.",
                'next_steps': ["Düzenli randevular", "İlaç uyumu", "Aile desteği"]
            },
            'moderate': {
                'immediate': ["İlaca bağlı kalın", "Haftada doktora görünün", "Tetikleyicilerden kaçının"],
                'self_care': ["Düzenli yaşam tarzı", "Sosyal destek", "Erken belirtileri öğrenin"],
                'professional': "Dikkatli tıbbi takip gerekli. İlacı bırakmayın.",
                'next_steps': ["Düzenli ilaç", "Psikoterapi", "Acil durum planı"]
            },
            'severe': {
                'immediate': [" Hemen doktoru arayın", "İlacı bırakmayın", "Aile desteği isteyin"],
                'self_care': ["Yoğun izleme", "İstikrarlı ortam", "Sıkı uyum"],
                'professional': " KRİTİK! Hastaneye yatış gerekebilir. Doktoru arayın: 182",
                'next_steps': ["Hemen değerlendirme", "İlaç ayarlaması", "Günlük izleme"]
            }
        }
    },

    'Autism': {
        'ar': {
            'mild': {
                'immediate': ["بيئة منظمة", "جداول بصرية", "راحة حسية عند الحاجة"],
                'self_care': ["وقت للاهتمامات الخاصة", "تفاعل اجتماعي تدريجي", "أدوات حسية"],
                'professional': "استشر متخصصاً في طيف التوحد للدعم.",
                'next_steps': ["تقييم شامل", "مجموعات دعم", "برامج مهارات"]
            }
        },
        'en': {
            'mild': {
                'immediate': ["Organized environment", "Visual schedules", "Sensory breaks as needed"],
                'self_care': ["Time for special interests", "Gradual social interaction", "Sensory tools"],
                'professional': "Consult autism spectrum specialist for support.",
                'next_steps': ["Comprehensive evaluation", "Support groups", "Skills programs"]
            }
        },
        'tr': {
            'mild': {
                'immediate': ["Düzenli ortam", "Görsel programlar", "Gerektiğinde duyusal molalar"],
                'self_care': ["Özel ilgi alanlarına zaman", "Kademeli sosyal etkileşim", "Duyusal araçlar"],
                'professional': "Destek için otizm spektrum uzmanına danışın: 0850 532 43 43",
                'next_steps': ["Kapsamlı değerlendirme", "Destek grupları", "Beceri programları"]
            }
        }
    },

    'Personality_Disorder': {
        'ar': {
            'mild': {
                'immediate': ["راقب ردود أفعالك", "تقنيات التكيف", "اطلب دعماً"],
                'self_care': ["تنظيم المشاعر", "تحسين العلاقات", "شفقة الذات"],
                'professional': "العلاج السلوكي الجدلي فعّال. استشر معالجاً متخصصاً.",
                'next_steps': ["علاج متخصص", "برامج منتظمة", "مجموعات دعم"]
            }
        },
        'en': {
            'mild': {
                'immediate': ["Monitor your reactions", "Coping techniques", "Request support"],
                'self_care': ["Emotion regulation", "Improve relationships", "Self-compassion"],
                'professional': "Dialectical Behavior Therapy effective. Consult specialized therapist.",
                'next_steps': ["Specialized therapy", "Regular programs", "Support groups"]
            }
        },
        'tr': {
            'mild': {
                'immediate': ["Tepkilerinizi izleyin", "Başa çıkma teknikleri", "Destek isteyin"],
                'self_care': ["Duygu düzenleme", "İlişkileri geliştirme", "Kendine şefkat"],
                'professional': "Diyalektik Davranış Terapisi etkili. Uzman terapiste danışın: 182",
                'next_steps': ["Uzman terapi", "Düzenli programlar", "Destek grupları"]
            }
        }
    },

    'Severe_Psychiatric_Disorders': {
        'ar': {
            'mild': {
                'immediate': [" طلب مساعدة طبية", "بيئة آمنة", "دعم الأحباء"],
                'self_care': ["التزام بالدواء", "فحوصات منتظمة", "تجنب التوتر"],
                'professional': " حالة خطيرة! اذهب لطوارئ المستشفى فوراً.",
                'next_steps': ["تقييم نفسي فوري", "علاج مكثف", "متابعة طويلة"]
            }
        },
        'en': {
            'mild': {
                'immediate': [" Request medical help", "Safe environment", "Loved ones support"],
                'self_care': ["Medication adherence", "Regular check-ups", "Avoid stress"],
                'professional': " SERIOUS! Go to hospital ER immediately.",
                'next_steps': ["Immediate psych evaluation", "Intensive treatment", "Long-term follow-up"]
            }
        },
        'tr': {
            'mild': {
                'immediate': [" Tıbbi yardım isteyin: 112", "Güvenli ortam", "Sevdiklerin desteği"],
                'self_care': ["İlaç uyumu", "Düzenli kontrolle", "Stresten kaçının"],
                'professional': "CİDDİ! Hemen hastane acil servisine gidin: 112",
                'next_steps': ["Hemen psikiyatrik değerlendirme", "Yoğun tedavi", "Uzun süreli takip"]
            }
        }
    }
}

# =============================================================================
#  ENHANCED ASSISTANT CLASS
# =============================================================================

class EnhancedMentalHealthAssistant:
    def __init__(self, classifier, translator, texts, questions, recommendations):
        self.classifier = classifier
        self.translator = translator
        self.texts = texts
        self.questions = questions
        self.recommendations = recommendations
        self.current_language = 'en'
        self.conversation_data = {
            'initial_input': '',
            'answers': [],
            'combined_text': '',
            'history': []
        }

    def detect_language(self, text: str) -> str:
        """كشف اللغة"""
        if not text.strip():
            return 'en'

        text_lower = text.lower()
        total = len([c for c in text if c.isalpha()])
        if total == 0:
            return 'en'

        arabic_chars = len([c for c in text if '\u0600' <= c <= '\u06FF'])
        arabic_ratio = arabic_chars / total

        turkish_chars = len([c for c in text_lower if c in ['ç', 'ğ', 'ı', 'ö', 'ş', 'ü']])
        turkish_words = len([w for w in text_lower.split() if any(t in w for t in ['iyi', 'güzel', 'yorgun', 'üzgün'])])
        turkish_ratio = (turkish_chars + turkish_words * 0.5) / total

        if arabic_ratio > 0.3:
            return 'ar'
        elif turkish_ratio > 0.05:
            return 'tr'
        else:
            return 'en'

    def get_user_input(self):
        """الحصول على مدخلات المستخدم"""
        print(self.texts[self.current_language]['welcome'])
        user_input = input(f"\n{self.texts[self.current_language]['share_feelings']}\n> ").strip()

        detected_lang = self.detect_language(user_input)
        if detected_lang != self.current_language:
            self.current_language = detected_lang
            print(f"\n{self.texts[self.current_language]['language_detected']} {self.current_language.upper()}")

        self.conversation_data['initial_input'] = user_input
        self.conversation_data['history'].append({'role': 'user', 'content': user_input})

        return user_input

    def ask_questions(self):
        lang = self.current_language
        questions_pool = self.questions[lang]

        selected = random.sample(questions_pool, min(5, len(questions_pool)))
        answers = []

        print(f"\n{self.texts[lang]['exploratory_title']}")
        print("=" * 60)

        for i, q in enumerate(selected, 1):
            print(f"\n{i}. {q}")
            answer = input("> ").strip()
            answers.append(answer)
            self.conversation_data['history'].append({'role': 'user', 'content': answer})

        self.conversation_data['answers'] = answers
        return answers

    def assess_severity(self, text: str, confidence: float) -> str:
        """تقييم الشدة بناءً على النص والثقة"""
        severity_keywords = {
            'severe': ['شديد', 'جداً', 'كثير', 'دائماً', 'لا أستطيع', 'مستحيل',
                      'severe', 'very', 'extremely', 'always', 'cannot', 'impossible',
                      'şiddetli', 'çok', 'sürekli', 'yapamıyorum', 'imkansız'],
            'moderate': ['أحياناً', 'غالباً', 'متوسط', 'صعب',
                        'sometimes', 'often', 'moderate', 'difficult',
                        'bazen', 'sık sık', 'orta', 'zor'],
            'mild': ['قليلاً', 'نادراً', 'خفيف', 'بسيط',
                    'slightly', 'rarely', 'mild', 'simple',
                    'biraz', 'nadiren', 'hafif', 'basit']
        }

        text_lower = text.lower()

        severe_count = sum(1 for keyword in severity_keywords['severe'] if keyword in text_lower)
        moderate_count = sum(1 for keyword in severity_keywords['moderate'] if keyword in text_lower)
        mild_count = sum(1 for keyword in severity_keywords['mild'] if keyword in text_lower)

        if severe_count >= 2 or confidence > 0.85:
            return 'severe'
        elif moderate_count >= 2 or confidence > 0.65:
            return 'moderate'
        else:
            return 'mild'

    def analyze(self) -> Tuple[str, float, str]:
        lang = self.current_language

        initial = self.conversation_data['initial_input']
        answers = self.conversation_data['answers']
        combined = initial + " " + " ".join(answers)
        self.conversation_data['combined_text'] = combined

        print(f"\n{self.texts[lang]['analyzing']}")

        try:
            if lang != 'en':
                combined = self.translator.translate(combined, lang, 'en')

            result = self.classifier(combined)
            all_predictions = {item['label']: item['score'] for item in result[0]}

            category, confidence = max(all_predictions.items(), key=lambda x: x[1])
            severity = self.assess_severity(combined, confidence)

            print(f" التحليل اكتمل")
            print(f" الفئة: {category} | الثقة: {confidence:.1%} | الشدة: {severity}")

            return category, confidence, severity, all_predictions

        except Exception as e:
            print(f" خطأ في التحليل: {e}")
            return "Normal", 0.5, "mild", {}

    def get_recommendations(self, category: str, severity: str) -> Dict:
        """الحصول على التوصيات"""
        lang = self.current_language

        if category not in self.recommendations:
            category = 'Normal'

        if lang not in self.recommendations[category]:
            lang = 'en'

        if severity not in self.recommendations[category][lang]:
            severity = 'mild'

        return self.recommendations[category][lang][severity]

    def display_results(self, category: str, confidence: float, severity: str, all_predictions: Dict):
        """عرض النتائج"""
        lang = self.current_language
        t = self.texts[lang]

        print(f"\n{'='*70}")
        print(f"  {t['results_title']}")
        print(f"{'='*70}")

        if category in ['Suicidal', 'Severe_Psychiatric_Disorders']:
            print("\n" + "" * 25)
            print("     URGENT / عاجل / ACİL DURUM  ")
            print("   This requires IMMEDIATE professional attention!")
            print("   هذه الحالة تتطلب عناية مهنية فورية!")
            print("   Bu durum ACİL profesyonel yardım gerektirir!")
            print("" * 25 + "\n")

        print(f"\n{t['category']} {category}")
        print(f"{t['confidence']} {confidence:.1%}")
        print(f"{t['severity']} {severity.upper()}")

        if all_predictions:
            for i, (label, score) in enumerate(sorted(all_predictions.items(),
                                                       key=lambda x: x[1], reverse=True)[:3], 1):
                bar = "" * int(score * 20)
                print(f"   {i}. {label:30s} {bar} {score:.1%}")

        # الحصول على التوصيات
        recs = self.get_recommendations(category, severity)

        print(f"\n{t['immediate_support']}")
        for i, action in enumerate(recs['immediate'], 1):
            print(f"   {i}. {action}")

        print(f"\n{t['self_care']}")
        for i, care in enumerate(recs['self_care'], 1):
            print(f"   {i}. {care}")

        print(f"\n{t['professional_guidance']}")
        print(f"   {recs['professional']}")

        print(f"\n{t['next_steps']}")
        for i, step in enumerate(recs['next_steps'], 1):
            print(f"   {i}. {step}")

        print(f"\n{'='*70}")
        print(f" {t['remember']}")
        print(f"{'='*70}\n")

    def save_session(self):
        """حفظ الجلسة"""
        lang = self.current_language
        t = self.texts[lang]

        save_prompt = input(f"{t['save_prompt']} ").strip().lower()
        yes_responses = ['نعم', 'yes', 'y', 'ن', 'ايه', 'evet', 'e']

        if save_prompt in yes_responses:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f'/content/drive/MyDrive/mental_health_{timestamp}.json'

            try:
                with open(filename, 'w', encoding='utf-8') as f:
                    json.dump({
                        'timestamp': timestamp,
                        'language': lang,
                        'data': self.conversation_data
                    }, f, ensure_ascii=False, indent=2)
                print(f" تم الحفظ: {filename}")
            except Exception as e:
                print(f" خطأ في الحفظ: {e}")

    def run(self):
        try:
            while True:
                self.get_user_input()

                self.ask_questions()

                category, confidence, severity, all_predictions = self.analyze()

                self.display_results(category, confidence, severity, all_predictions)


                self.save_session()

                cont = input(f"\n{self.texts[self.current_language]['continue_chat']} ").strip().lower()
                yes_responses = ['نعم', 'yes', 'y', 'ن', 'ايه', 'evet', 'e']

                if cont not in yes_responses:
                    print(f"\n {self.texts[self.current_language]['remember']}")
                    print("\n Take care! / اعتني بنفسك! / Kendine iyi bak! \n")
                    break
                else:
                    print("\n" + "="*70)
                    print("جلسة جديدة / New Session / Yeni Oturum")
                    print("="*70 + "\n")
                    self.conversation_data = {
                        'initial_input': '',
                        'answers': [],
                        'combined_text': '',
                        'history': self.conversation_data['history'].copy()
                    }

            return self.conversation_data['history']

        except KeyboardInterrupt:
            print("\n\n تم إيقاف الجلسة / Session stopped / Oturum durduruldu")
            return None
        except Exception as e:
            print(f"\n خطأ: {e}")
            import traceback
            traceback.print_exc()
            return None

# =============================================================================
#  MAIN EXECUTION
# =============================================================================

if __name__ == "__main__":
    print("\n" + "="*70)
    print("        Enhanced Multilingual Mental Health Assistant")
    print("          نظام الصحة النفسية المحسّن متعدد اللغات")
    print("         Gelişmiş Çok Dilli Ruh Sağlığı Asistanı")
    print("="*70)
    print("\n الميزات المحسّنة / Enhanced Features / Gelişmiş Özellikler:")
    print("    10 فئات نفسية / 10 Mental Health Categories")
    print("    3 لغات كاملة / 3 Complete Languages (AR/EN/TR)")
    print("   تقييم الشدة / Severity Assessment (Mild/Moderate/Severe)")
    print("   توصيات موسعة / Comprehensive Recommendations")
    print("    أسئلة معمقة / In-depth Questions")
    print("    ترجمة محسنة / Enhanced Translation")
    print("    جاهز للاختبار / Ready for Console Testing")
    print("="*70)
    print("\n  تنبيه مهم / Important Notice / Önemli Uyarı:")
    print("    هذا النظام أداة مساعدة وليس بديلاً عن التشخيص الطبي")
    print("    This system is a support tool, not a medical diagnosis substitute")
    print("    Bu sistem bir destek aracıdır, tıbbi teşhis yerine geçmez")
    print("\n" + "="*70 + "\n")

    assistant = EnhancedMentalHealthAssistant(
        classifier=classifier,
        translator=translation_engine,
        texts=MULTILINGUAL_SYSTEM,
        questions=ENHANCED_QUESTIONS,
        recommendations=COMPREHENSIVE_RECOMMENDATIONS
    )

    conversation = assistant.run()

    if conversation:
        print(f"\n ملخص الجلسة / Session Summary / Oturum Özeti:")
        print(f"   إجمالي التفاعلات / Total Interactions: {len(conversation)}")
        languages = set(msg.get('language', 'unknown') for msg in conversation if 'language' in msg)
        if languages:
            print(f"   اللغات المستخدمة / Languages Used: {', '.join(languages)}")
        print("\n اكتملت الجلسة بنجاح / Session Completed Successfully / Oturum Başarıyla Tamamlandı!\n")

    print("="*70)
    print(" شكراً لاستخدام النظام / Thank you / Teşekkürler! ")
    print("="*70 + "\n")